# Generated by Django 4.2.18 on 2025-02-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("entity_id", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AgeDistribution",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("less_than_10", models.IntegerField()),
                ("age_10_to_19", models.IntegerField()),
                ("age_20_to_29", models.IntegerField()),
                ("age_30_to_39", models.IntegerField()),
                ("age_40_to_49", models.IntegerField()),
                ("age_50_to_59", models.IntegerField()),
                ("age_60_to_69", models.IntegerField()),
                ("age_70_to_79", models.IntegerField()),
                ("age_80_to_89", models.IntegerField()),
                ("age_90_and_above", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Age Distributions",
            },
        ),
        migrations.CreateModel(
            name="EthnicityDistribution",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("european", models.IntegerField()),
                ("maori", models.IntegerField()),
                ("pacific_peoples", models.IntegerField()),
                ("asian", models.IntegerField()),
                ("middle_eastern_latin_american_african", models.IntegerField()),
                ("other_ethnicity", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Ethnicity Distributions",
            },
        ),
        migrations.CreateModel(
            name="GenderDistribution",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("male", models.IntegerField()),
                ("female", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Gender Distributions",
            },
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("never_married", models.IntegerField()),
                ("married", models.IntegerField()),
                ("separated", models.IntegerField()),
                ("divorced", models.IntegerField()),
                ("widowed", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Marital Status Distributions",
            },
        ),
        migrations.CreateModel(
            name="ReligiousAffiliation",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("christian", models.IntegerField()),
                ("buddhist", models.IntegerField()),
                ("hindu", models.IntegerField()),
                ("muslim", models.IntegerField()),
                ("jewish", models.IntegerField()),
                ("other_religion", models.IntegerField()),
                ("no_religion", models.IntegerField()),
                ("not_stated", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Religious Affiliations",
            },
        ),
        migrations.CreateModel(
            name="TotalPopulation",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Total Population",
            },
        ),
    ]
