# Generated by Django 4.2.18 on 2025-02-26 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("region_type", models.CharField(max_length=50)),
                ("parent_region_id", models.CharField(blank=True, max_length=50, null=True)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                ("population", models.IntegerField(blank=True, null=True)),
                (
                    "area_sq_km",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("subs", models.JSONField(blank=True, null=True)),
                ("supers", models.JSONField(blank=True, null=True)),
                ("other_ids", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "regions",
            },
        ),
        migrations.CreateModel(
            name="AgeDistribution",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("less_than_10", models.IntegerField()),
                ("age_10_to_19", models.IntegerField()),
                ("age_20_to_29", models.IntegerField()),
                ("age_30_to_39", models.IntegerField()),
                ("age_40_to_49", models.IntegerField()),
                ("age_50_to_59", models.IntegerField()),
                ("age_60_to_69", models.IntegerField()),
                ("age_70_to_79", models.IntegerField()),
                ("age_80_to_89", models.IntegerField()),
                ("age_90_and_above", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Age Distributions",
            },
        ),
        migrations.CreateModel(
            name="EthnicityDistribution",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("sinhalese", models.IntegerField()),
                ("sl_tamil", models.IntegerField()),
                ("ind_tamil", models.IntegerField()),
                ("sl_moor", models.IntegerField()),
                ("burgher", models.IntegerField()),
                ("malay", models.IntegerField()),
                ("sl_chetty", models.IntegerField()),
                ("bharatha", models.IntegerField()),
                ("other_eth", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Ethnicity Distributions",
            },
        ),
        migrations.CreateModel(
            name="GenderDistribution",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("male", models.IntegerField()),
                ("female", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Gender Distributions",
            },
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("never_married", models.IntegerField()),
                ("married_registered", models.IntegerField()),
                ("married_customary", models.IntegerField()),
                ("separated_legally", models.IntegerField()),
                ("separated_non_legal", models.IntegerField()),
                ("divorced", models.IntegerField()),
                ("widowed", models.IntegerField()),
                ("not_stated", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Marital Status Distributions",
            },
        ),
        migrations.CreateModel(
            name="ReligiousAffiliation",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("buddhist", models.IntegerField()),
                ("hindu", models.IntegerField()),
                ("islam", models.IntegerField()),
                ("roman_catholic", models.IntegerField()),
                ("other_christian", models.IntegerField()),
                ("other", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Religious Affiliations",
            },
        ),
        migrations.CreateModel(
            name="TotalPopulation",
            fields=[
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="population_stats.region",
                    ),
                ),
                ("total_population", models.IntegerField()),
                ("year", models.IntegerField(default=2012)),
            ],
            options={
                "verbose_name_plural": "Total Population",
            },
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["region_type"], name="regions_region__17554e_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["code"], name="regions_code_aa1ecb_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["parent_region_id"], name="regions_parent__037562_idx"),
        ),
    ]
