# Generated by Django 4.2.18 on 2025-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("population_stats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ethnicitydistribution",
            old_name="asian",
            new_name="bharatha",
        ),
        migrations.RenameField(
            model_name="ethnicitydistribution",
            old_name="european",
            new_name="burgher",
        ),
        migrations.RenameField(
            model_name="ethnicitydistribution",
            old_name="maori",
            new_name="ind_tamil",
        ),
        migrations.RenameField(
            model_name="ethnicitydistribution",
            old_name="middle_eastern_latin_american_african",
            new_name="malay",
        ),
        migrations.RenameField(
            model_name="ethnicitydistribution",
            old_name="other_ethnicity",
            new_name="other_eth",
        ),
        migrations.RenameField(
            model_name="ethnicitydistribution",
            old_name="pacific_peoples",
            new_name="sinhalese",
        ),
        migrations.AddField(
            model_name="ethnicitydistribution",
            name="sl_chetty",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ethnicitydistribution",
            name="sl_moor",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ethnicitydistribution",
            name="sl_tamil",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
