# Generated by Django 4.2.18 on 2025-02-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("population_stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="centroid_altitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Altitude of the region's centroid in meters",
                max_digits=10,
                null=True,
            ),
        ),
    ]
