# Generated by Django 4.2.18 on 2025-02-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("population_stats", "0002_rename_asian_ethnicitydistribution_bharatha_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maritalstatus",
            old_name="married",
            new_name="married_customary",
        ),
        migrations.RenameField(
            model_name="maritalstatus",
            old_name="separated",
            new_name="married_registered",
        ),
        migrations.AddField(
            model_name="maritalstatus",
            name="not_stated",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="maritalstatus",
            name="separated_legally",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="maritalstatus",
            name="separated_non_legal",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
