# Generated by Django 4.2.18 on 2025-02-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("population_stats", "0002_region_centroid_altitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="eqs",
            field=models.JSONField(
                blank=True, help_text="List of equivalent region IDs", null=True
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="ints",
            field=models.JSONField(
                blank=True, help_text="List of intersecting region IDs", null=True
            ),
        ),
    ]
