# Generated by Django 4.2.18 on 2025-02-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("population_stats", "0003_rename_married_maritalstatus_married_customary_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="religiousaffiliation",
            old_name="christian",
            new_name="islam",
        ),
        migrations.RenameField(
            model_name="religiousaffiliation",
            old_name="jewish",
            new_name="other",
        ),
        migrations.RenameField(
            model_name="religiousaffiliation",
            old_name="muslim",
            new_name="other_christian",
        ),
        migrations.RenameField(
            model_name="religiousaffiliation",
            old_name="no_religion",
            new_name="roman_catholic",
        ),
        migrations.RemoveField(
            model_name="religiousaffiliation",
            name="not_stated",
        ),
        migrations.RemoveField(
            model_name="religiousaffiliation",
            name="other_religion",
        ),
    ]
