# Generated by Django 4.2.18 on 2025-02-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("population_stats", "0003_region_eqs_region_ints"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="fips",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="hasc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
